version: '3'
services:
  web:
    build: .
    container_name: web
    environment:
      - DB_PATH=${DB_PATH}
      - DB_PORT=${DB_PORT}
      - API_PATH=${API_PATH}
      - API_PORT=${API_PORT}
    ports:
      - "${API_PORT}:${API_PORT}"
  mongo:
    image: "mongo:latest"
    container_name: mongo